import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import GroupKFold, GridSearchCV
from sklearn.ensemble import RandomForestClassifier

def prepare_ml_dataset(csv_path: Path):
    """
    Loads the pre-assembled features and target dataset, extracting the 
    temporal coordinate (year) for cross-validation grouping.

    Parameters
    ----------
    csv_path : pathlib.Path
        Path to the 'features_target.csv' file generated by the feature 
        construction script.

    Returns
    -------
    features : pandas.DataFrame
        The feature dataset containing only Principal Components.
    target : pandas.Series
        The binary target variable series for the machine learning model.
    groups : pandas.Series
        The temporal grouping variable (years) extracted for Cross-Validation.
    """
    print(f"Loading dataset from: {csv_path}")
    df = pd.read_csv(csv_path)
    
    # Ensure 'id' is set as the index following previous preprocessing steps
    if 'id' in df.columns:
        df = df.set_index('id')
        
    if 'forecast_time' not in df.columns:
        raise ValueError("The dataset must contain a 'forecast_time' column for temporal splitting.")
        
    if 'target' not in df.columns:
        raise ValueError("The dataset must contain a 'target' column.")

    # Extract grouping variable (year)
    df['forecast_time'] = pd.to_datetime(df['forecast_time'])
    groups = df['forecast_time'].dt.year

    # Isolate target and features
    target = df['target']
    features = df.drop(columns=['forecast_time', 'target'])
    
    print(f"Dataset ready: {features.shape[0]} samples, {features.shape[1]} features.")
    return features, target, groups


def train_rf_gridsearch(features: pd.DataFrame, target: pd.Series, groups: pd.Series, 
                        param_grid: dict, output_dir: Path, test_size: float = 0.2):
    """
    Splits the data based on whole years, initializes a Random Forest, 
    and runs a GridSearchCV utilizing GroupKFold to prevent temporal data leakage.
    Saves all cross-validation results to disk.

    Parameters
    ----------
    features : pandas.DataFrame
        The input features for the model.
    target : pandas.Series
        The target variable to predict.
    groups : pandas.Series
        The grouping variable (years) to ensure strict temporal splitting.
    param_grid : dict
        Dictionary with parameters names as keys and lists of parameter settings to try.
    output_dir : pathlib.Path
        Directory where the GridSearch results CSV should be saved.
    test_size : float, optional
        The approximate proportion of the dataset to include in the test split.
        The algorithm will convert this to a whole number of years. Default is 0.2.

    Returns
    -------
    grid_search : sklearn.model_selection.GridSearchCV
        The fitted GridSearchCV object containing results and the best estimator.
    features_test : pandas.DataFrame
        The subset of features used for testing.
    target_test : pandas.Series
        The subset of target variables used for testing.
    """
    # 1. Determine whole-year splitting to match desired test_size
    unique_years = np.sort(groups.unique())
    n_total_years = len(unique_years)
    
    n_test_years = max(1, int(round(n_total_years * test_size)))
    n_train_years = n_total_years - n_test_years
    
    train_years = unique_years[:n_train_years]
    test_years = unique_years[n_train_years:]
    
    # Create boolean masks
    train_idx = groups.isin(train_years)
    test_idx = groups.isin(test_years)
    
    features_train, features_test = features[train_idx], features[test_idx]
    target_train, target_test = target[train_idx], target[test_idx]
    groups_train = groups[train_idx]
    
    # 2. Print exact split statistics
    actual_test_pct = (len(features_test) / len(features)) * 100
    print(f"\n--- Data Split Summary ---")
    print(f"Requested test size: {test_size * 100:.1f}%")
    print(f"Train: {n_train_years} years ({train_years[0]} to {train_years[-1]}), {len(features_train)} samples.")
    print(f"Test:  {n_test_years} years ({test_years[0]} to {test_years[-1]}), {len(features_test)} samples.")
    print(f"Actual resulting test percentage: {actual_test_pct:.2f}%\n")

    # 3. Cross-Validation Configuration
    gkf = GroupKFold(n_splits=min(5, n_train_years))
    
    # 4. Base Model Definition
    rf = RandomForestClassifier(random_state=42, n_jobs=-1)
    
    print("Starting GridSearchCV...")
    
    grid_search = GridSearchCV(
        estimator=rf, 
        param_grid=param_grid, 
        cv=gkf, 
        scoring='f1', 
        n_jobs=-1,
        verbose=3  # This makes the terminal "talk" constantly with timings
    )
    
    # 5. Model fitting
    grid_search.fit(features_train, target_train, groups=groups_train)
    
    # 6. Save ALL results (not just the best) to CSV for offline study
    output_dir.mkdir(parents=True, exist_ok=True)
    results_csv_path = output_dir / 'grid_search_all_results.csv'
    results_df = pd.DataFrame(grid_search.cv_results_)
    results_df.to_csv(results_csv_path, index=False)
    print(f"\nAll GridSearch results successfully saved to: {results_csv_path}")
    
    print("\nBest Hyperparameters Found:")
    print(grid_search.best_params_)
    print(f"Best CV F1-Score: {grid_search.best_score_:.4f}")
    
    return grid_search, features_test, target_test